In [ ]:
import numpy as np

#First step we have to do that is creating array

In [ ]:
array=np.array([1,2,3,4,5,6])
print(array)

[1 2 3 4 5 6]


In [ ]:
zero_array=np.zeros((2,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
one_array=np.ones((2,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
range_array=np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


In [ ]:
linespace_array=np.linspace(0,10,5)
print(linespace_array)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6])
print(array)
zero_array=np.zeros((3,4))
print(zero_array)
ones_array=np.ones((4,6))
print(ones_array)
range_array=np.arange(0,10,3)
print(range_array)
linespace_array=np.linspace(0,1,5)
print(linespace_array)
print(array.shape)
print(array.dtype)
print(array.ndim)
print(array.size)
print(array[0])
print(array[-5:])
print(array[2:5])
#modify an element
array[0]=10
print(array)
ones_array[1,2] =10
print(ones_array)





[1 2 3 4 5 6]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[0 3 6 9]
[0.   0.25 0.5  0.75 1.  ]
(6,)
int64
1
6
1
[2 3 4 5 6]
[3 4 5]
[10  2  3  4  5  6]
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


In [ ]:
print(ones_array[:2,:3])

[[ 1.  1.  1.]
 [ 1.  1. 10.]]


In [ ]:
arr3=np.ones((3,3))
arr3[1,1]=99
print(arr3)

[[ 1.  1.  1.]
 [ 1. 99.  1.]
 [ 1.  1.  1.]]


#practice exercise of day 1


In [ ]:
#practice Exercise Day1
import numpy as np
number=np.arange(10,60,10)
print(number)
zero_arr=np.zeros((3,3))
print(zero_arr)
ones_arr=np.ones((4,5))
print(ones_arr)
num=np.arange(0,15)
print(num)
line=np.linspace(0,1,5)
print(line)
#Arrays Properties
print(number.shape)
print(number.size)
print(number.ndim)
print(number.dtype)
#3️⃣ Indexing & Slicing
print(number[:1])
print(number[-1:])
print(number[2:4])
#Create a 3x3 2D array and access the middle element.
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
print(array[1,1])
print(array[2:2])
array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array)
print(array[1,1])
print(array[:2,:2])
#5️⃣ Mini Challenge
#Create a 3x3 array of ones and change the middle element to 10.
array=np.ones((3,3))
print(array)
array[1,1]=10
print(array)
arr=np.arange(1,11)
print(arr)
print(arr[arr>5])
array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array)
print(array[:2,:2])
array=np.random.randint(1,20,size=(4,4))
print(array)
print(array[:2,:2])





[10 20 30 40 50]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.   0.25 0.5  0.75 1.  ]
(5,)
5
1
int64
[10]
[50]
[30 40]


#Day2

#Numpy Operation And Statistics

In [ ]:
a=np.array([1,2,3,4])
b=np.array([2,4,5,8])
"""c= a + b
print(c)"""
print(a + b)
print(a - b)
print(a * b)
print(a / b)
#2️⃣ Aggregate Functions (Basic Statistics)
x=np.array([1,2,3,4,5,6])
print(x.sum())
print(x.mean())
print(x.max())
print(x.min())
print(x.std())
print(x.var())
#3️⃣ Axis in 2D Arrays
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))
#4️⃣ Broadcasting (Important)
x=np.array([1,2,3,4,5,6])
print(x+10)
row=np.array([1,2,3,7,8,9])
print(x + row)











[ 3  6  8 12]
[-1 -2 -2 -4]
[ 2  8 15 32]
[0.5 0.5 0.6 0.5]
21
3.5
6
1
1.707825127659933
2.9166666666666665
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
[11 12 13 14 15 16]
[ 2  4  6 11 13 15]
[ 3  7 11 15]
[1 1 1 1]
[ 2 12 30 56]
[2.         1.33333333 1.2        1.14285714]
[      2      64    7776 2097152]


In [ ]:
#practice
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)
x = np.array([10, 15, 20, 25, 30])
print(x.sum())
print(x.mean())
print(x.max())
print(x.min())
print(x.std())
print(x.var())
arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(arr.mean(axis=1))

[ 3  7 11 15]
[1 1 1 1]
[ 2 12 30 56]
[2.         1.33333333 1.2        1.14285714]
[      2      64    7776 2097152]
100
20.0
30
10
7.0710678118654755
50.0
225
[60 75 90]
[ 30  75 120]
[10. 25. 40.]


#Day3

#🔄 NumPy Revision – Day 1 + Day 2

#1️⃣ Array Creation & Basics (Day 1)

In [ ]:
"""arr1=np.arange(10,50,10)
print(arr1)"""
arr1=np.arange(10,60,10)
print(arr1)
zero=np.zeros((3,3))
print(zero)


[10 20 30 40 50]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:

"""
zero=np.zeros((3,3))
print(zero)
one=np.ones((3,3))
print(one)
arr1=np.arange(0,15)
print(arr1)
line=np.linspace(0,1,5)
print(line)
#properties
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)"""
#indexing and slicing
"""arr1=np.arange(10,60,10)
print(arr1[1])
print(arr1[3])
print(arr1[-1:])
print(arr1[2:5])"""
"""one=np.ones((3,3))
print(one)
print(one[1,1])
one[1,1]=10
print(one)"""
#2️⃣ Array Operations & Statistics (Day 2)
"""arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(arr.mean())
"""
"""arr1=np.arange(10,60,10)
print(arr1)
print(arr1.max())
print(arr1.min())
print(arr1.mean())
print(arr1.var())
print(arr1.std())"""
"""array=np.random.randint(1,10,size=(4,4))
print(array)
print(array.shape)
print(array.size)
print(array.ndim)
print(array.dtype)
print(array.sum())
print(array.mean())
print(array.sum(axis=0))
print(array.max(axis=1))
#mathmatics operation
print(array.max())
print(array.min())
print(array.mean())
print(array.var())
print(array.std())
print(array[1])
print(array[-1:])
print(array[:1])
print(array[2,1])
print(array[:2,:3])
array[1,1] =10
print(array)"""
arr=np.arange(1,13)
print(f"Original Array: {arr}")
reshaped_arr=arr.reshape(3,4)
print(f"Reshaped Array: {reshaped_arr}")
array=np.arange(1,21)
print(array)
bool=array[array >10]
print(bool)



Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]


#📘 Day 3 – Broadcasting & Advanced Operations

In [ ]:
import numpy as np
arr=np.array([1,2,3])
print(arr +5)
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
print(mat + np.array([10,20,30]))
a= np.array([1,2,3])
b= np.array([3,8,9])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)
mat = np.array([[1, 2],
                [3, 4]])

print("Transpose:\n", mat.T)
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
print("Dot product:\n", np.dot(a, b))
"""array= np.arange(1,10)
print(array)
reshape=array.reshape(3,3)
print(reshape)
arr=np.array([1,2,3])
print(arr + 10)
print(arr * 10)
"""
array=np.random.randint(1,10,size=(4,4))
print(array)
print(f"Transpose:\n {array.T}")
arr= array[array >6]
print(arr)


[6 7 8]
[[11 22 33]
 [14 25 36]]
[ 4 10 12]
[-2 -6 -6]
[ 3 16 27]
[0.33333333 0.25       0.33333333]
[    1   256 19683]


#📑 Day 3 – Practice Exercises

In [ ]:
#Q1. Broadcasting
array=np.array([1,2,3,4,5])
print(array + 100)
#Create a 2D array of shape (3,3) filled with numbers 1–9. Add [10,20,30] to each row.
arr=np.arange(1,10).reshape(3,3)
print(arr)
print(arr + np.array([2,3,4]))

[101 102 103 104 105]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


#📑 Day 3 – Practice Exercises

In [ ]:
import numpy as np
"""array=np.array([1,2,3,4,5])
print(array + 100)
arr=np.random.randint(1,10, size=(3,3))
print(arr + np.array([10,20,30]))"""
"""a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)"""
"""arr=np.random.randint(1,7, size=(2,2))
print(arr.T)"""
"""A = [[1,2],
     [3,4]]
B = [[5,6],
     [7,8]]
print(np.dot(A,B))"""
"""array=np.random.randint(1,10,size=(3,3))
arr= (array .T)
print(np.dot(array,arr))"""
arr=np.arange(1,50,20)
print(arr)
print(arr >25)
array=arr[arr>25]
print(array)



[ 1 21 41]
[False False  True]
[41]


#day 4

In [ ]:
#1️⃣ Stacking Arrays
"""import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Horizontal Stack:",np.hstack([a,b]))
print("Vertical Stack:",np.vstack([a,b]))"""
#2️⃣ Splitting Arrays
"""arr=np.arange(1,10).reshape(3,3)
print(arr)
print(np.hsplit(arr,3))
print(np.vsplit(arr,3))"""
#print(np.hsplit(arr,3))
#3️⃣ Fancy Indexing
"""arr=np.array([10,20,30,40,50])
indexes=[0,2,4]
print(arr[indexes])"""
"""mat = np.arange(1, 10).reshape(3, 3)
print("Matrix:\n", mat)
print("Select (0,0), (1,1), (2,2):", mat[[0, 1, 2], [0, 1, 2]])
"""
#4️⃣ Real-world Mini Practice
marks=np.array([23,45,67,89,34,53,37])
print(marks[marks >50])
print(np.sort(marks)[-3:])





[67 89 53]
[53 67 89]
