In [ ]:
import numpy as np
patient=np.random.randint(20,80, size=(15,4))
print(patient)
print(patient.shape)
print(patient.size)
print(patient.ndim)
print(patient.dtype)
print(patient[0])
print(patient[:,-3])
print(patient[:1,:1])
print(patient[2,1])
print(patient[:,3])
print(patient[-3:])

print(patient[:,-3:])
print(patient[1:3,1:3])
#Print the first patient’s record.
print(patient[0])
#Print all patient ages.
print(patient[:,0])
#Slice the last 5 patients.
print(patient[-5:])
#Extract a sub-matrix: patients 5–8, only BP & Cholesterol.
print(patient[1:5,1:8])
#Find the average age of patients.
avg_age=patient[:,0].mean()
print(avg_age)
bp=patient[:,1].max()
print(bp)
total_chl=patient[:,2].sum()
print(total_chl)
print(patient.sum(axis=0))
print(patient.sum(axis=1))

 # Add +5 to all heart rates (as if a measurement correction).
heart=patient[:,3]
print(heart + 5)
#Find patients with BP > 140.
bp=patient[:,1]
print(bp)
print(bp[bp>40])"""
"""Cholesterol=patient[:,2]
print(Cholesterol)
print(Cholesterol[Cholesterol < 200])
older=patient[:,0] >60
print(older)
patient[older,1] +=10
print(patient)
print(patient.T)
BMI=np.random.randint(20,80, size=(15,1))
patient=np.hstack((patient,BMI))
print(patient)
new=np.random.randint(20,80,size=(1,5))
patient=np.vstack((patient,new))
print(patient)
#Split the patients into two groups (first 7, next 8).
group1=patient[:7, :]
group2=patient[7:, :]
print(group1)
print(group2)
group1,group2=np.split(patient,2)
print(group1)
print(group2)

patient[[2, 5, 10, 12], :]
print(patient)
heart_rate=patient[:,3]
sorted=np.argsort(heart_rate)
top=sorted[-3:]
print(top)










[[26 32 75 45]
 [23 79 61 21]
 [22 39 35 41]
 [46 74 65 73]
 [43 27 31 20]
 [35 23 54 48]
 [72 65 67 25]
 [70 70 33 37]
 [26 54 64 30]
 [55 33 76 21]
 [27 62 71 70]
 [78 50 79 30]
 [68 45 50 35]
 [74 74 49 66]
 [20 55 77 63]]
[[26 32 75 45 41]
 [23 79 61 21 53]
 [22 39 35 41 32]
 [46 74 65 73 66]
 [43 27 31 20 69]
 [35 23 54 48 55]
 [72 65 67 25 68]
 [70 70 33 37 28]
 [26 54 64 30 54]
 [55 33 76 21 71]
 [27 62 71 70 64]
 [78 50 79 30 48]
 [68 45 50 35 64]
 [74 74 49 66 32]
 [20 55 77 63 75]]
[[26 32 75 45 41]
 [23 79 61 21 53]
 [22 39 35 41 32]
 [46 74 65 73 66]
 [43 27 31 20 69]
 [35 23 54 48 55]
 [72 65 67 25 68]
 [70 70 33 37 28]
 [26 54 64 30 54]
 [55 33 76 21 71]
 [27 62 71 70 64]
 [78 50 79 30 48]
 [68 45 50 35 64]
 [74 74 49 66 32]
 [20 55 77 63 75]
 [31 70 60 67 55]]
[15 10  3]


In [ ]:
print(patient[0])
print(patient[2])
print(patient[:,3])
print(patient[:,-2:])
print(patient[-3:])
print(patient[1:3,1:3])
print(patient[:2,:2])




[49 33 38 52]
[71 60 55 39]
[52 50 39 75 54 20 45 78 24 50 21 37 34 39 34]
[[38 52]
 [71 50]
 [55 39]
 [67 75]
 [44 54]
 [76 20]
 [67 45]
 [57 78]
 [68 24]
 [65 50]
 [32 21]
 [47 37]
 [39 34]
 [76 39]
 [46 34]]
[[68 63 39 34]
 [69 57 76 39]
 [71 34 46 34]]
[[38 71]
 [60 55]]
[[49 33]
 [21 38]]


In [ ]:
#Find patients with BP > 140.
bp=patient[:,1]
print(bp)
print(bp[bp>40])

[23 78 76 70 39 49 51 78 21 60 40 68 25 51 40]
[78 76 70 49 51 78 60 68 51]
