#Theme: Student Performance Analytics


In [ ]:
import numpy as np
student=np.random.randint(0,100,size=(10,3))
print(student)
print(student.sum())

print
print(student.shape)
print(student.size)
print(student.ndim)
print(student.dtype)
print(student[0])
print(student[:,2])
print(student[4,1])
print(student[9])
print(student[:,0])
print(student[2,1])
print(student[1:6,2])

print(student[0:5])

print(student[:-5])
print(student[0:2])
print(student[3:7,1])
print(student[4:6,1:3])
print(student[0:3,1:3])
print(student[0:3,0])
print(student[0:3])
print(student[:, -2])
print(student[4:6,1:3])"""
"""arr=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr)
arr=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(arr)
print(arr>5)
#print(arr[arr>5])"""
student=np.random.randint(0,100,size=(10,3))
print(student)
print(student.sum())
print(student.sum(axis=0))
print(student.sum(axis=1))
print(student.mean(axis=0))
print(student.max(axis=0))
print(student.min(axis=0))
print(student.std(axis=0))
print(student.var(axis=0))
total=student.sum(axis=0)
print(np.argmax(total))
print(student.max(axis=0))
import numpy as np

student=np.random.randint(0,100,size=(10,3))
print(student)
print(student + 5)
marks=(student.mean())
print(marks)
student_mean=student - marks
print(student_mean)
print(student[student > 70])
print(student[:,0] >80)
print(student[student < 40].sum())
computer=np.random.randint(0,100,size=(10,1))
print(computer)
student=np.hstack((student,computer))
print(student)
new=np.random.randint(0,100,size=(2,4))
print(new)
student=np.vstack((student,new))
print(student)
group1,group2=np.split(student,2)
print(group1)
print(group2)













[[81 85 27]
 [84 78 54]
 [21 97 25]
 [66 52 66]
 [31 21 74]
 [32 49 65]
 [12  9 35]
 [28 69 41]
 [57 52 58]
 [66 86 16]]
[[ 86  90  32]
 [ 89  83  59]
 [ 26 102  30]
 [ 71  57  71]
 [ 36  26  79]
 [ 37  54  70]
 [ 17  14  40]
 [ 33  74  46]
 [ 62  57  63]
 [ 71  91  21]]
51.233333333333334
[[ 29.76666667  33.76666667 -24.23333333]
 [ 32.76666667  26.76666667   2.76666667]
 [-30.23333333  45.76666667 -26.23333333]
 [ 14.76666667   0.76666667  14.76666667]
 [-20.23333333 -30.23333333  22.76666667]
 [-19.23333333  -2.23333333  13.76666667]
 [-39.23333333 -42.23333333 -16.23333333]
 [-23.23333333  17.76666667 -10.23333333]
 [  5.76666667   0.76666667   6.76666667]
 [ 14.76666667  34.76666667 -35.23333333]]
[81 85 84 78 97 74 86]
[ True  True False False False False False False False False]
257
[[43]
 [52]
 [47]
 [47]
 [26]
 [57]
 [77]
 [35]
 [40]
 [ 7]]
[[81 85 27 43]
 [84 78 54 52]
 [21 97 25 47]
 [66 52 66 47]
 [31 21 74 26]
 [32 49 65 57]
 [12  9 35 77]
 [28 69 41 35]
 [57 52 58 40]
 [6

[[80]
 [87]
 [10]
 [38]
 [23]
 [38]
 [86]
 [49]
 [66]
 [25]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 10