In [ ]:
import numpy as np
student=np.random.randint(0,100,size=(10,3))
print(student)
print(student[0])
print(student[:,-1])
#🔹 Step 2 – Basic Stats (Day 2)
print(student.sum())
print(student.mean())
print(student.max())
print(student + 5)
print(student[student >70])
print(student .T)
computer=np.random.randint(0,100,size=(10,1))
student=np.hstack((student,computer))
print(student)
group1,group2=np.split(student,2)
print(group1)
print(group2)
np.select= student[[1,4,6]]
print(np.select)
english=student[:,2]
print(np.sort(english)[-3:])






[[86 50 90]
 [71 58 85]
 [ 1  1 27]
 [ 3 23 51]
 [13 17 35]
 [99 58 37]
 [76 58 22]
 [71 56  6]
 [43 81 33]
 [ 2 36 72]]
[86 50 90]
[90 85 27 51 35 37 22  6 33 72]
1361
45.36666666666667
99
[[ 91  55  95]
 [ 76  63  90]
 [  6   6  32]
 [  8  28  56]
 [ 18  22  40]
 [104  63  42]
 [ 81  63  27]
 [ 76  61  11]
 [ 48  86  38]
 [  7  41  77]]
[86 90 71 85 99 76 71 81 72]
[[86 71  1  3 13 99 76 71 43  2]
 [50 58  1 23 17 58 58 56 81 36]
 [90 85 27 51 35 37 22  6 33 72]]
[[86 50 90 24]
 [71 58 85 13]
 [ 1  1 27 43]
 [ 3 23 51 14]
 [13 17 35  2]
 [99 58 37 76]
 [76 58 22 24]
 [71 56  6 10]
 [43 81 33 86]
 [ 2 36 72 69]]
[[86 50 90 24]
 [71 58 85 13]
 [ 1  1 27 43]
 [ 3 23 51 14]
 [13 17 35  2]]
[[99 58 37 76]
 [76 58 22 24]
 [71 56  6 10]
 [43 81 33 86]
 [ 2 36 72 69]]
[[71 58 85 13]
 [13 17 35  2]
 [76 58 22 24]]
[72 85 90]


#📝 Day 1 Project: Student Marks Manager (Arrays & Indexing)

In [ ]:
student=np.random.randint(0,100,size=(5,3))
print(student)
print(student[0])
print(student[-1])
print(student[:,1])
print(student[:3])
print(student[-2:])
print(student[2,1])
student[2,1]=10
print(student)"""
"""computer=np.random.randint(0,100,size=(5,1))
print(computer)
student=np.hstack((student,computer))
print(student)"""
"""print(student[2,:])
print(student[2,1])
print(student[:2])
print(student[:,-2:])
print(student[1:3,1:3])
print(student.sum())
print(student.mean())
print(student.max())
print(student.min())
print(student.sum(axis=0))
print(student[:5].mean())
group1,group2=np.split(student,2)
print(group1)
print(group1)











NameError: name 'np' is not defined