In [ ]:
import numpy as np
trip=np.random.randint(50,500,size=(20,5))
print(trip)

print(trip.shape)
print(trip.size)
print(trip.ndim)
print(trip.dtype)
print(trip[5])
print(trip[:5])
print(trip[:,-2:])
print(trip[:,-3:])
print(trip[:,-0])
print(trip[5:10,1])
print(trip[:,0])
print(trip[-4:,3:5])
avg_distance=trip[:,0].mean()
print(avg_distance)
high=trip[:,2].max()
print(high)
cost=trip[:,3].sum()
print(cost)
rating=trip[:,4].min()
print(rating)
print(trip.sum(axis=1))
print(trip.sum(axis=0))
distance=trip[:,0]
print(trip[distance >300])
rating=trip[:,4]
print(trip[rating <3])
duration=trip[:,1]
increase=trip[duration >5]
print(increase)
print(increase + 20)
fuel=trip[:,2]
rating=trip[:,4]
cond1= fuel < 100
cond2= rating >4
print(trip[cond1 & cond2])
distance=trip[:, 0]
print(distance + 10)
duration=trip[:,1]
print(duration * 60)
rating=trip[:,4]
print(rating/5)
driver_age=np.random.randint(25,60,size=(20,1))
print(driver_age)
print(np.hstack((trip,driver_age)))
new_row=np.random.randint(50,500,size=(1,5))
print(np.vstack((new_row,trip)))
print(trip.shape)
trip_new=np.vstack((trip,new_row))
print(trip_new.shape)
group1,group2=np.split(trip,2)
print(group1)
print(group2)
cost=trip[:,3]
print(np.sort(cost))
rating=trip[:,4]
top_3=np.argsort(rating)[-3:]
print(top_3)
selected_trip=trip[[2, 7, 15],:]
print(selected_trip)
cond=trip[:,0]
high=trip[:,2]
efficiency=cond/high
print(efficiency)
best_index=efficiency.argmax()
print(best_index)
print(trip[best_index])

[303 343 326 154 420]
[109 141 485 246 149 156 417  75 398 400  95 288 235 464 316 196 122 218
 203 470]
[[ 73 433]
 [302 457]
 [372 203]
 [304 249]]


[0.28684211 0.30718954 0.97389558 2.7032967  1.12030075 2.22857143
 1.49462366 0.24115756 7.80392157 1.45985401 0.37254902 1.87012987
 0.47188755 0.9626556  0.95180723 0.60122699 0.55454545 0.46382979
 0.80555556 0.95918367]
8
[398 154  51 320 231]
